@startuml

object Organization {
    <#lightblue,#black>|= id |= identifier |= name |
    <#white>|  |  |  |
}

object Person {
    <#lightblue,#black>|= id |= identifier |= name |
    <#white>|  |  |  |
}

@enduml
